//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoardFarm.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HoardFarm.Data.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string ConfigWindow_And {
            get {
                return ResourceManager.GetString("ConfigWindow_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable statistic gathering.
        /// </summary>
        internal static string ConfigWindow_DisableStatisticGathering {
            get {
                return ResourceManager.GetString("ConfigWindow_DisableStatisticGathering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables global gathering of runtimes and found hoards.
        ///Purely used to build a accurate global statistic.
        ///Only sends time of a run, if a hoard is found and the travel time to hoard.
        ///Character, timestamp or any other identifying info will NEVER send!.
        /// </summary>
        internal static string ConfigWindow_DisableStatisticGathering_Help {
            get {
                return ResourceManager.GetString("ConfigWindow_DisableStatisticGathering_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actually no really much to configure here..
        /// </summary>
        internal static string ConfigWindow_GreetingText {
            get {
                return ResourceManager.GetString("ConfigWindow_GreetingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string ConfigWindow_Language {
            get {
                return ResourceManager.GetString("ConfigWindow_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string ConfigWindow_Language_de {
            get {
                return ResourceManager.GetString("ConfigWindow_Language_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client-Language.
        /// </summary>
        internal static string ConfigWindow_Language_default {
            get {
                return ResourceManager.GetString("ConfigWindow_Language_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string ConfigWindow_Language_en {
            get {
                return ResourceManager.GetString("ConfigWindow_Language_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string ConfigWindow_Language_fr {
            get {
                return ResourceManager.GetString("ConfigWindow_Language_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        internal static string ConfigWindow_Language_ja {
            get {
                return ResourceManager.GetString("ConfigWindow_Language_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        internal static string ConfigWindow_Language_ko {
            get {
                return ResourceManager.GetString("ConfigWindow_Language_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        internal static string ConfigWindow_Language_zh {
            get {
                return ResourceManager.GetString("ConfigWindow_Language_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &quot;Open Hoardfarm&quot;-Overlay.
        /// </summary>
        internal static string ConfigWindow_OpenHoardfarmOverlay {
            get {
                return ResourceManager.GetString("ConfigWindow_OpenHoardfarmOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset local statistics.
        /// </summary>
        internal static string ConfigWindow_ResetStatistics {
            get {
                return ResourceManager.GetString("ConfigWindow_ResetStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %d seconds.
        /// </summary>
        internal static string ConfigWindow_Seconds {
            get {
                return ResourceManager.GetString("ConfigWindow_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slower mode.
        /// </summary>
        internal static string ConfigWindow_SlowMode {
            get {
                return ResourceManager.GetString("ConfigWindow_SlowMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow mode will wait some seconds before requeue again.
        ///Not really necessary, but makes some people feel better..
        /// </summary>
        internal static string ConfigWindow_SlowMode_Help {
            get {
                return ResourceManager.GetString("ConfigWindow_SlowMode_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support on Ko-fi.
        /// </summary>
        internal static string ConfigWindow_SupportKofi {
            get {
                return ResourceManager.GetString("ConfigWindow_SupportKofi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wanna support me? Buy me a coffee!.
        /// </summary>
        internal static string ConfigWindow_SupportMe {
            get {
                return ResourceManager.GetString("ConfigWindow_SupportMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HoardFarm Config.
        /// </summary>
        internal static string ConfigWindow_Title {
            get {
                return ResourceManager.GetString("ConfigWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait between:.
        /// </summary>
        internal static string ConfigWindow_WaitBetween {
            get {
                return ResourceManager.GetString("ConfigWindow_WaitBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Hoardfarm.
        /// </summary>
        internal static string DeepDungeonMenuOverlay_OpenHoardfarm {
            get {
                return ResourceManager.GetString("DeepDungeonMenuOverlay_OpenHoardfarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the Hoard Farm window.
        /// /hoardfarm config | c → Open the config window.
        /// /hoardfarm enable | e → Enable farming mode.
        /// /hoardfarm disable | d → Disable farming mode.
        /// /hoardfarm toggle | t → Toggle farming mode.
        ///.
        /// </summary>
        internal static string HoardFarm_CommandHelp {
            get {
                return ResourceManager.GetString("HoardFarm_CommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string HoardFarm_Status_Done {
            get {
                return ResourceManager.GetString("HoardFarm_Status_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering HoH.
        /// </summary>
        internal static string HoardFarm_Status_EnteringHoH {
            get {
                return ResourceManager.GetString("HoardFarm_Status_EnteringHoH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string HoardFarm_Status_Error {
            get {
                return ResourceManager.GetString("HoardFarm_Status_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please prepare before starting.
        ///You need at least one Intuition Pomander
        ///and one Concealment..
        /// </summary>
        internal static string HoardFarm_Status_Error_MinimalSetup {
            get {
                return ResourceManager.GetString("HoardFarm_Status_Error_MinimalSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please prepare before starting.
        ///Floor One is not supported..
        /// </summary>
        internal static string HoardFarm_Status_Error_Unprepared {
            get {
                return ResourceManager.GetString("HoardFarm_Status_Error_Unprepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string HoardFarm_Status_Finished {
            get {
                return ResourceManager.GetString("HoardFarm_Status_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoard Found.
        /// </summary>
        internal static string HoardFarm_Status_HoardFound {
            get {
                return ResourceManager.GetString("HoardFarm_Status_HoardFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaving.
        /// </summary>
        internal static string HoardFarm_Status_Leaving {
            get {
                return ResourceManager.GetString("HoardFarm_Status_Leaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to Hoard.
        /// </summary>
        internal static string HoardFarm_Status_MoveToHoard {
            get {
                return ResourceManager.GetString("HoardFarm_Status_MoveToHoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving to HoH.
        /// </summary>
        internal static string HoardFarm_Status_MoveToHoH {
            get {
                return ResourceManager.GetString("HoardFarm_Status_MoveToHoH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Hoard.
        /// </summary>
        internal static string HoardFarm_Status_NoHoard {
            get {
                return ResourceManager.GetString("HoardFarm_Status_NoHoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player died.
        /// </summary>
        internal static string HoardFarm_Status_PlayerDied {
            get {
                return ResourceManager.GetString("HoardFarm_Status_PlayerDied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retainer Running.
        /// </summary>
        internal static string HoardFarm_Status_RetainerRunning {
            get {
                return ResourceManager.GetString("HoardFarm_Status_RetainerRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string HoardFarm_Status_Running {
            get {
                return ResourceManager.GetString("HoardFarm_Status_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching.
        /// </summary>
        internal static string HoardFarm_Status_Searching {
            get {
                return ResourceManager.GetString("HoardFarm_Status_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching {0}.
        /// </summary>
        internal static string HoardFarm_Status_SearchingObject {
            get {
                return ResourceManager.GetString("HoardFarm_Status_SearchingObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        internal static string HoardFarm_Status_Timeout {
            get {
                return ResourceManager.GetString("HoardFarm_Status_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreachable.
        /// </summary>
        internal static string HoardFarm_Status_Unreachable {
            get {
                return ResourceManager.GetString("HoardFarm_Status_Unreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        internal static string HoardFarm_Status_Waiting {
            get {
                return ResourceManager.GetString("HoardFarm_Status_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for vnavmesh.
        /// </summary>
        internal static string HoardFarm_Status_WaitingNavmesh {
            get {
                return ResourceManager.GetString("HoardFarm_Status_WaitingNavmesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do retainers:.
        /// </summary>
        internal static string MainWindow_DoRetainers {
            get {
                return ResourceManager.GetString("MainWindow_DoRetainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If ALL Retainer are done.
        /// </summary>
        internal static string MainWindow_DoRetainers_AllDone {
            get {
                return ResourceManager.GetString("MainWindow_DoRetainers_AllDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If ANY Retainer is done.
        /// </summary>
        internal static string MainWindow_DoRetainers_AnyDone {
            get {
                return ResourceManager.GetString("MainWindow_DoRetainers_AnyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This features requires AutoRetainer to be installed and configured..
        /// </summary>
        internal static string MainWindow_DoRetainers_AutoretainerNeeded {
            get {
                return ResourceManager.GetString("MainWindow_DoRetainers_AutoretainerNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ports to Limsa Lominsa and runs retainers between runs if done..
        /// </summary>
        internal static string MainWindow_DoRetainers_Port {
            get {
                return ResourceManager.GetString("MainWindow_DoRetainers_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the current world name or Inventory slot..
        /// </summary>
        internal static string MainWindow_DoRetainers_WrongWorld {
            get {
                return ResourceManager.GetString("MainWindow_DoRetainers_WrongWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable HoardFarm Mode.
        /// </summary>
        internal static string MainWindow_EnableHoardFarmMode {
            get {
                return ResourceManager.GetString("MainWindow_EnableHoardFarmMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm Mode:.
        /// </summary>
        internal static string MainWindow_FarmMode {
            get {
                return ResourceManager.GetString("MainWindow_FarmMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficiency.
        /// </summary>
        internal static string MainWindow_FarmMode_Efficiency {
            get {
                return ResourceManager.GetString("MainWindow_FarmMode_Efficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficiency mode will search and try to find every hoard.
        ///&gt;20% of the hoards are unreachable from start.
        ///It will take some seconds to find it.
        ///This mode is still recommended..
        /// </summary>
        internal static string MainWindow_FarmMode_Efficiency_Help {
            get {
                return ResourceManager.GetString("MainWindow_FarmMode_Efficiency_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety.
        /// </summary>
        internal static string MainWindow_FarmMode_Safety {
            get {
                return ResourceManager.GetString("MainWindow_FarmMode_Safety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety mode will NOT search for hoards.
        ///It instantly leaves if the hoard is unreachable. 
        ///Safer and faster runs but you will miss a lot of hoards.
        ///It will take longer overall..
        /// </summary>
        internal static string MainWindow_FarmMode_Safety_Help {
            get {
                return ResourceManager.GetString("MainWindow_FarmMode_Safety_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Config.
        /// </summary>
        internal static string MainWindow_OpenConfig {
            get {
                return ResourceManager.GetString("MainWindow_OpenConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Help.
        /// </summary>
        internal static string MainWindow_OpenHelp {
            get {
                return ResourceManager.GetString("MainWindow_OpenHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall:.
        /// </summary>
        internal static string MainWindow_Overall {
            get {
                return ResourceManager.GetString("MainWindow_Overall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress: {0} / {1}.
        /// </summary>
        internal static string MainWindow_Progress {
            get {
                return ResourceManager.GetString("MainWindow_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffer mode. Unable to calculate the remaining time..
        /// </summary>
        internal static string MainWindow_ProgressNoTime {
            get {
                return ResourceManager.GetString("MainWindow_ProgressNoTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damn it will take ages. Trust me.
        /// </summary>
        internal static string MainWindow_ProgressZero {
            get {
                return ResourceManager.GetString("MainWindow_ProgressZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will need at least {0} of farming to complete the achievement..
        /// </summary>
        internal static string MainWindow_RemainingTime {
            get {
                return ResourceManager.GetString("MainWindow_RemainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will need at least {0} Days and {1} of farming to complete the achievement..
        /// </summary>
        internal static string MainWindow_RemainingTimeDays {
            get {
                return ResourceManager.GetString("MainWindow_RemainingTimeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savegame:.
        /// </summary>
        internal static string MainWindow_Savegame {
            get {
                return ResourceManager.GetString("MainWindow_Savegame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savegame 1.
        /// </summary>
        internal static string MainWindow_Savegame_1 {
            get {
                return ResourceManager.GetString("MainWindow_Savegame_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savegame 2.
        /// </summary>
        internal static string MainWindow_Savegame_2 {
            get {
                return ResourceManager.GetString("MainWindow_Savegame_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics:.
        /// </summary>
        internal static string MainWindow_Statistics {
            get {
                return ResourceManager.GetString("MainWindow_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Session.
        /// </summary>
        internal static string MainWindow_Statistics_CurrentSession {
            get {
                return ResourceManager.GetString("MainWindow_Statistics_CurrentSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found: {0}   ({1:0.##} %).
        /// </summary>
        internal static string MainWindow_Statistics_Found {
            get {
                return ResourceManager.GetString("MainWindow_Statistics_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs: {0}.
        /// </summary>
        internal static string MainWindow_Statistics_Runs {
            get {
                return ResourceManager.GetString("MainWindow_Statistics_Runs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop After:.
        /// </summary>
        internal static string MainWindow_StopAfter {
            get {
                return ResourceManager.GetString("MainWindow_StopAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Hoards.
        /// </summary>
        internal static string MainWindow_StopAfter_Hoards {
            get {
                return ResourceManager.GetString("MainWindow_StopAfter_Hoards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string MainWindow_StopAfter_Minutes {
            get {
                return ResourceManager.GetString("MainWindow_StopAfter_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs.
        /// </summary>
        internal static string MainWindow_StopAfter_Runs {
            get {
                return ResourceManager.GetString("MainWindow_StopAfter_Runs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support me ♥.
        /// </summary>
        internal static string MainWindow_SupportMe {
            get {
                return ResourceManager.GetString("MainWindow_SupportMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: {0}.
        /// </summary>
        internal static string MainWindow_Time {
            get {
                return ResourceManager.GetString("MainWindow_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: {0}   (Ø {1}).
        /// </summary>
        internal static string MainWindow_TimeWithAverage {
            get {
                return ResourceManager.GetString("MainWindow_TimeWithAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HoardFarm {0}.
        /// </summary>
        internal static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to run:.
        /// </summary>
        internal static string MainWindow_UnableToRun {
            get {
                return ResourceManager.GetString("MainWindow_UnableToRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This features requires &quot;vnavmesh&quot; to be installed..
        /// </summary>
        internal static string MainWindow_vnavmeshRequired {
            get {
                return ResourceManager.GetString("MainWindow_vnavmeshRequired", resourceCulture);
            }
        }
    }
}
